#!chezscheme
;;; chandler/pack/launchers.ss --- 启动器生成(原 pack.ss §5)
;;;
;;; 启动器住在 bin/<app>,比 <mt> 层高一级,故包根仍是它的父目录。
;;;
;;; **不设任何路径 env**(D8:APP_ROOT 已去除)—— 库搜索走 `--libdirs`
;;; 挂上的 <mt>/ 对象根,native 与资源都由生成的 loader / resource-path
;;; 扫 (library-directories) 定位。

(library (chandler pack launchers)
  (export sh-head ps1-head
          launcher-sh-skiff launcher-ps1-skiff
          boots-flags launcher-sh-stock launcher-ps1-stock
          write-launcher!)
  (import (chezscheme)
          (chandler fs)
          (chandler proc)
          (chandler layout))

  (define (sh-head)
    (string-append
      "#!/bin/sh\n"
      "# generated by chandler pack -- do not edit\n"
      "HERE=$(CDPATH= cd -- \"$(dirname -- \"$0\")/..\" && pwd)\n"))

  (define (ps1-head)
    ;; PowerShell 无 exec,故每个启动器都以重抛 $LASTEXITCODE 收尾;$args 在函数内是
    ;; 该函数的参数,故顶层先捕获再 splat;PS 7.3+ 原生命令非零退出会抛,显式关掉。
    (string-append
      "#!/usr/bin/env pwsh\n"
      "# generated by chandler pack -- do not edit\n"
      "$PSNativeCommandUseErrorActionPreference = $false\n"
      "$PackArgs = $args\n"
      "$Here = Split-Path -Parent $PSScriptRoot\n"))

;; skiff 启动器 = pack 规范的薄 shim:指好 boot,直接 `exec skiff --program run.sps`
;; (与 stock 启动器同构 —— 各自指好 runtime + boot,通过 --program 跑 run.sps;
;; skiff pack 不再走 `skiff --app`)。SKIFF_BOOT_DIR 是必须的:skiff 按 exe 相对找
;; boot(<exedir>/../lib/skiff/boot),包内 bin/ + lib/chez/ 对不上它;而 boot 必须在
;; 进程有堆之前注册,远早于 --program 被解析,env 是唯一可用的交接方式。
  (define (launcher-sh-skiff name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (sh-head)
        "export SKIFF_BOOT_DIR=\"$HERE/lib/chez\"\n"
        "exec \"$HERE/bin/skiff\" -q --program \"$HERE/" runner "\" \"$@\"\n")))

  (define (launcher-ps1-skiff name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (ps1-head)
        "$env:SKIFF_BOOT_DIR = \"$Here/lib/chez\"\n"
        "& \"$Here/bin/skiff.exe\" -q --program \"$Here/" runner "\" @PackArgs\n"
        "exit $LASTEXITCODE\n")))

  ;; stock Chez:绝对 -b 链(bake designs/22 机制 C —— 最稳,exe 名任意,相对 -b 不可用)。
  ;; petite.boot 恒随;scheme.boot 只在 runtime=scheme 时随(部署态只 fasl 载入预编译
  ;; .so,petite 单独即可,包更小)。
  (define (boots-flags runtime prefix)
    (let ([p (string-append prefix "/lib/chez/")])
      (string-append "-b \"" p "petite.boot\""
                     (if (eq? runtime 'scheme) (string-append " -b \"" p "scheme.boot\"") ""))))

  (define (launcher-sh-stock runtime name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (sh-head)
        "exec \"$HERE/bin/scheme\" "
        (boots-flags runtime "$HERE")
        " -q --program \"$HERE/" runner "\" \"$@\"\n")))

  (define (launcher-ps1-stock runtime name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (ps1-head)
        "& \"$Here/bin/scheme.exe\" "
        (boots-flags runtime "$Here")
        " -q --program \"$Here/" runner "\" @PackArgs\n"
        "exit $LASTEXITCODE\n")))

  ;; 按 machine-type 选 sh / .ps1。ta6nt 包只能在 Windows 上产,故 .ps1 这条在 Linux
  ;; 上不被 `chandler pack` 走到;生成器本身另由 PowerShell 验收渲染后实跑。
  (define (write-launcher! root app sh ps1)
    (let ([bindir (join-paths root "bin")])
      (ensure-dir bindir)
      (if (windows-mt? (current-machine-type))
          (write-text (join-paths bindir (string-append app ".ps1")) ps1)
          (let ([f (join-paths bindir app)])
            (write-text f sh)
            (run-status "chmod" (list "+x" f))))))
  )
