#!chezscheme
;;; chandler/pack/launchers.ss --- 启动器生成(原 pack.ss §5)
;;;
;;; 启动器住在 bin/<app>,比 <mt> 层高一级,故包根仍是它的父目录。
;;;
;;; **不设任何路径 env**(D8:APP_ROOT 已去除)—— 库搜索走 `--libdirs`
;;; 挂上的 <mt>/ 对象根,native 与资源都由生成的 loader / resource-path
;;; 扫 (library-directories) 定位。

(library (chandler pack launchers)
  (export sh-head cmd-head
          launcher-sh-skiff launcher-cmd-skiff
          boots-flags launcher-sh-stock launcher-cmd-stock
          write-launcher!)
  (import (chezscheme)
          (chandler fs)
          (chandler proc)
          (chandler layout))

  (define (sh-head)
    (string-append
      "#!/bin/sh\n"
      "# generated by chandler pack -- do not edit\n"
      "HERE=$(CDPATH= cd -- \"$(dirname -- \"$0\")/..\" && pwd)\n"))

  ;; Windows 侧是 `.cmd`,不是 `.ps1`(D34)—— **分发态的底线是只依赖 cmd.exe**:
  ;; pwsh 从不预装、ExecutionPolicy 可能拒跑未签名脚本、`.PS1` 也不在默认 PATHEXT 里。
  ;; 解包即用的包不该要求用户先装个 shell 再改执行策略。
  ;;
  ;; `%~dp0` = 脚本所在目录(带尾反斜杠),故 `%~dp0..` 就是包根。**不 `cd`** ——
  ;; 保持 UNC 路径下可用,也不改变子进程的工作目录。
  ;; cmd 无 exec,故末尾显式 `exit /b %errorlevel%` 转发退出码。
  (define (cmd-head)
    (string-append
      "@echo off\r\n"
      "rem generated by chandler pack -- do not edit\r\n"
      "setlocal\r\n"
      "set \"HERE=%~dp0..\"\r\n"))

;; skiff 启动器 = pack 规范的薄 shim:指好 boot,直接 `exec skiff --program run.sps`
;; (与 stock 启动器同构 —— 各自指好 runtime + boot,通过 --program 跑 run.sps;
;; skiff pack 不再走 `skiff --app`)。SKIFF_BOOT_DIR 是必须的:skiff 按 exe 相对找
;; boot(<exedir>/../lib/skiff/boot),包内 bin/ + lib/chez/ 对不上它;而 boot 必须在
;; 进程有堆之前注册,远早于 --program 被解析,env 是唯一可用的交接方式。
  (define (launcher-sh-skiff name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (sh-head)
        "export SKIFF_BOOT_DIR=\"$HERE/lib/chez\"\n"
        "exec \"$HERE/bin/skiff\" -q --program \"$HERE/" runner "\" \"$@\"\n")))

  (define (launcher-cmd-skiff name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (cmd-head)
        "set \"SKIFF_BOOT_DIR=%HERE%\\lib\\chez\"\r\n"
        "\"%HERE%\\bin\\skiff.exe\" -q --program \"%HERE%\\" (backslashes runner) "\" %*\r\n"
        "exit /b %errorlevel%\r\n")))

  ;; stock Chez:绝对 -b 链(bake designs/22 机制 C —— 最稳,exe 名任意,相对 -b 不可用)。
  ;; petite.boot 恒随;scheme.boot 只在 runtime=scheme 时随(部署态只 fasl 载入预编译
  ;; .so,petite 单独即可,包更小)。
  (define (boots-flags runtime prefix)
    (let ([p (string-append prefix "/lib/chez/")])
      (string-append "-b \"" p "petite.boot\""
                     (if (eq? runtime 'scheme) (string-append " -b \"" p "scheme.boot\"") ""))))

  (define (launcher-sh-stock runtime name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (sh-head)
        "exec \"$HERE/bin/scheme\" "
        (boots-flags runtime "$HERE")
        " -q --program \"$HERE/" runner "\" \"$@\"\n")))

  ;; `boots-flags` **两侧共用同一个函数**(Chez 在 Windows 上也接受 `/`),
  ;; 只在出口把分隔符归一成反斜杠 —— 既不多一份实现,生成的批处理里也不会出现
  ;; `"%HERE%/lib/chez/petite.boot"` 这种半 Unix 半 Windows 的路径。
  (define (launcher-cmd-stock runtime name version)
    (let ([runner (string-append "share/chez/" name "/" version "/.chandler/run.sps")])
      (string-append
        (cmd-head)
        "\"%HERE%\\bin\\scheme.exe\" "
        (backslashes (boots-flags runtime "%HERE%"))
        " -q --program \"%HERE%\\" (backslashes runner) "\" %*\r\n"
        "exit /b %errorlevel%\r\n")))

  ;; 包内相对路径 → 反斜杠形。Chez 自己两种都吃,但批处理里的路径是给人看也给人
  ;; 改的,混着写会让人以为是两套路径。
  (define (backslashes s)
    (list->string (map (lambda (c) (if (char=? c #\/) #\\ c)) (string->list s))))

  ;; 按 machine-type 选 sh / .cmd。ta6nt 包只能在 Windows 上产,故 .cmd 这条在 Linux
  ;; 上不被 `chandler pack` 走到 —— 生成器本身由 launcher-parity 测试对拍两侧结构。
  ;; `.cmd` 必须 CRLF(cmd.exe 对 LF-only 的标签/goto 会出错),由 write-text-crlf 保证。
  (define (write-launcher! root app sh cmd)
    (let ([bindir (join-paths root "bin")])
      (ensure-dir bindir)
      (if (windows-mt? (current-machine-type))
          (write-text-crlf (join-paths bindir (string-append app ".cmd")) cmd)
          (let ([f (join-paths bindir app)])
            (write-text f sh)
            (make-executable! f)))))      ; C9:先前是 `chmod +x` 子进程
  )
