#!chezscheme
;;; chandler/pack/manifest-writer.ss --- pack.manifest 写入(原 pack.ss §7)

(library (chandler pack manifest-writer)
  (export write-pack-manifest!)
  (import (chezscheme)
          (chandler fs)
          (chandler util)
          (chandler layout)
          (chandler hash)
          (chandler pack paths)
          (chandler pack natives))

  (define (manifest-head app version runtime entry main-proc ver mt skiff-ver)
    (let ([bootp "lib/chez/"]
          [binp  "bin/"])
      (string-append
        ";; generated by chandler pack (designs/09)\n"
        "(pack\n"
        "  (format 1)\n"
        "  (app \"" app "\") (version \"" version "\")\n"
        "  (target (chez-version \"" ver "\") (machine-type " mt ")"
        ;; skiff 的 verify-target! 精确匹配 skiff-version,故只有捆了 skiff 的包才钉它;
        ;; stock 包不带任何 skiff API 依赖,声明一个全开区间 → 同一个 stock 包在
        ;; bin/<mt>/scheme 与任意 `skiff --app` 下通吃。
        (if skiff-ver
            (string-append " (skiff-version \"" skiff-ver "\")")
            " (skiff-compat \">=0.0.0\")")
        ")\n"
        (if (eq? runtime 'skiff)
            (string-append
              "  (runtime (kind skiff) (exe \"" binp "skiff\")\n"
              "           (boots \"" bootp "petite.boot\" \"" bootp "scheme.boot\""
              " \"" bootp "skiff.boot\"))\n")
            (string-append
              "  (runtime (kind " (symbol->string runtime) ") (exe \"" binp "scheme\")\n"
              "           (boots \"" bootp "petite.boot\""
              (if (eq? runtime 'scheme) (string-append " \"" bootp "scheme.boot\"") "")
              "))\n"))
        "  (lib-dirs \"" mt "\")\n"
        "  (entry (library " (datum->string entry) ") (main " (symbol->string main-proc) "))\n")))

  ;; (native <soname> "<rel>") —— `skiff --app`(与 stock Chez 上 run.sps 的部署侧
  ;; prelude)在 import 入口库
  ;; 之前统一 load-shared-object 这些(pack 规范 §4:infra 载 native,库只写
  ;; foreign-procedure)。按组装后的树实扫,故应用自己的 native 也在内。空则省略。
  ;; 对象根不止一个 —— app 与每个 dep 各有 <libdir>/<name>/<version>/<mt>/,
  ;; 故逐 version-root 扫描;<rel> 相对包根(带 share/chez/ 前缀)。
  (define (manifest-native-lines root)
    (let ([mt (current-machine-type)]
          [libdir (pack-libdir root)]
          [out '()])
      (for-each
        (lambda (name-dir)
          (let ([nd (join-paths libdir name-dir)])
            (when (file-directory? nd)
              (for-each
                (lambda (ver-dir)
                  (let ([obj (join-paths nd ver-dir mt)])
                    (when (file-directory? obj)
                      (for-each
                        (lambda (segs)
                          (let* ([rel (string-join segs "/")]
                                 [ndir (join-paths obj rel "native")]
                                 [pre (string-append "share/chez/" name-dir "/" ver-dir "/" mt "/"
                                                     rel "/native/")])
                            (for-each
                              (lambda (f)
                                (set! out (cons (string-append "    (" (path-root f)
                                                               " \"" pre f "\")\n")
                                                out)))
                              (native-files-in ndir))))
                        (native-libs-under obj)))))
                (list-sort string<? (dir-entries nd))))))
        (if (file-directory? libdir) (list-sort string<? (dir-entries libdir)) '()))
      (let ([entries (reverse out)])
        (if (null? entries) "" (string-append "  (native\n" (apply string-append entries) "    )\n")))))

  ;; (files …):每个文件的 sha256 + 字节数。**按需**校验(chandler verify-pack / 补丁前),
  ;; 不在每次启动跑 —— 启动只做廉价的目标三元组比对。pack.manifest 最后写,故不自哈。
  (define (manifest-files-lines root)
    (apply string-append
      (map (lambda (abs)
             (let ([rel (relativize root abs)])
               (string-append "    (\"" rel "\" (sha256 \"" (sha256-file abs)
                              "\") (size " (number->string (file-byte-size abs)) "))\n")))
           (list-sort string<? (files-under root)))))

  ;; file-byte-size 已收入 (chandler fs),直接复用。

  (define (write-pack-manifest! root app version runtime entry main-proc ver mt skiff-ver)
    (write-text (join-paths root "pack.manifest")
      (string-append
        (manifest-head app version runtime entry main-proc ver mt skiff-ver)
        (manifest-native-lines root)
        "  (files\n"
        (manifest-files-lines root)
        "    ))\n")))
  )
