#!chezscheme
;;; chandler/pack/snapshot.ss --- 清单快照 + 依赖路径(原 pack.ss §3)
;;;
;;; datum->string 已收入 (chandler util),直接复用。

(library (chandler pack snapshot)
  (export write-app-manifest! dep-src-root dep-obj-dir)
  (import (chezscheme)
          (chandler fs)
          (chandler util)
          (chandler layout)
          (chandler install)
          (chandler lock))

  ;; .chandler/chandler-manifest.ss —— 应用清单快照,落在
  ;; <libdir>/<name>/<version>/.chandler/chandler-manifest.ss,与 install 字节级统一。
  ;; 项目有 chandler-manifest.ss 时 install-project-payload! 已拷过(幂等);
  ;; 没有(--name/--entry 临时打包)则合成一份最小清单。
  (define (write-app-manifest! project libdir app version entry main-proc)
    (let* ([vr (version-root libdir app version)]
           [dir (join-paths vr ".chandler")]
           [dst (join-paths dir "chandler-manifest.ss")]
           [src (project-manifest-path project)])
      (ensure-dir dir)
      (if (file-exists? src)
          (copy-file src dst)
          (write-text dst
            (string-append
              ";; generated by chandler pack -- no chandler-manifest.ss in the source project\n"
              "(manifest (format 1) (name \"" app "\") (version \"" version "\")\n"
              "  (app (entry " (datum->string entry) ") (main " (symbol->string main-proc) ")))\n")))))

  ;; 一个依赖在 _vendor 里的源码根(= 它的库搜索根,也是 `chandler build` 的 cwd)
  (define (dep-src-root project d)
    (vendor-dir project (locked-dep-name d)))

  ;; 该依赖的编译产物树:它自己的 _build/<mt>/
  (define (dep-obj-dir project d)
    (join-paths (dep-src-root project d) "_build" (current-machine-type)))
  )
