#!chezscheme
;;; tests/run-tests.sps --- 汇总运行 tests/chandler/* 全部 suite
;;;   scheme --libdirs . --program tests/run-tests.sps   (搜索根 = 仓库根)
;;; 非零退出码表失败。新增测试库 → prefix import + 在 all-suites 挂一行。

(import (chezscheme)
        (tests chandler harness)
        (prefix (tests chandler util) util:)
        (prefix (tests chandler fs) fs:)
        (prefix (tests chandler sexp) sexp:)
        (prefix (tests chandler layout) layout:)
        (prefix (tests chandler runtime-paths) runtime-paths:)
        (prefix (tests chandler version) version:)
        (prefix (tests chandler manifest) manifest:)
        (prefix (tests chandler lock) lock:)
        (prefix (tests chandler proc) proc:)
        (prefix (tests chandler fetch) fetch:)
        (prefix (tests chandler resolve) resolve:)
         (prefix (tests chandler install) install:)
         (prefix (tests chandler activate) activate:)
         (prefix (tests chandler cli) cli:)
         (prefix (tests chandler registry) registry:)
         (prefix (tests chandler build) build:)
          (prefix (tests chandler pack) pack:)
          (prefix (tests chandler base) base:)
          (prefix (tests chandler task-engine) task-engine:)
          (prefix (tests chandler miniregex) miniregex:)
          (prefix (tests chandler recipe) recipe:)
          (prefix (tests chandler import-graph) import-graph:)
          (prefix (tests chandler compile) compile:)
          (prefix (tests chandler native-build) native-build:)
          (prefix (tests chandler cli-make) cli-make:)
          (prefix (tests chandler env) env:)
          (prefix (tests chandler registered) registered:)
          (prefix (tests chandler cli-runtime-env) cli-runtime-env:)
          (prefix (tests chandler pack-verifier-parity) pack-verifier-parity:))

(define all-suites
  (list
    (cons 'util util:suite)
    (cons 'fs fs:suite)
    (cons 'sexp sexp:suite)
    (cons 'layout layout:suite)
    (cons 'runtime-paths runtime-paths:suite)
    (cons 'version version:suite)
    (cons 'manifest manifest:suite)
    (cons 'lock lock:suite)
    (cons 'proc proc:suite)
    (cons 'fetch fetch:suite)
    (cons 'resolve resolve:suite)
    (cons 'install install:suite)
    (cons 'activate activate:suite)
    (cons 'cli cli:suite)
    (cons 'registry registry:suite)
    (cons 'build build:suite)
    (cons 'pack pack:suite)
    (cons 'base base:suite)
    (cons 'task-engine task-engine:suite)
    (cons 'miniregex miniregex:suite)
    (cons 'recipe recipe:suite)
    (cons 'import-graph import-graph:suite)
    (cons 'compile compile:suite)
    (cons 'native-build native-build:suite)
    (cons 'cli-make cli-make:suite)
    (cons 'env env:suite)
    (cons 'registered registered:suite)
    (cons 'cli-runtime-env cli-runtime-env:suite)
    (cons 'pack-verifier-parity pack-verifier-parity:suite)))

(exit (if (run-suites all-suites) 0 1))
