#!chezscheme
;;; chandler/cli/selfinstall.ss --- chandler install-self / uninstall-self
;;;
;;; **自安装基于 bake install**(生态闭环):库树的拷贝完全委托给 `bake install`
;;; (读本仓 recipe.ss 的 install-task,装进 Chez lib dir 并写 bake 卸载清单);
;;; chandler 只额外补一个**运行时发现启动器**(bin/chandler,skiff 优先 → Chez),
;;; 这是 bake 不管的部分。卸载据 bake 清单删库 + 删启动器,不依赖源码目录。
;;;
;;; 落点(与 bake install-task 的 target 对齐):
;;;   user(默认) → ~/.local/share/chez/lib + ~/.local/bin/chandler
;;;   --global    → /usr/local/share/chez/lib + /usr/local/bin/chandler(需 root)

(library (chandler cli selfinstall)
  (export cmd-install-self cmd-uninstall-self
          self-libdir self-bindir self-launcher self-runtimes bake-command)
  (import (chezscheme)
          (chandler util)
          (chandler fs)
          (chandler proc)                     ; 调 bake / chmod
          (chandler layout)
          (chandler cli args))                ; flag?

  ;; 运行时发现顺序:skiff 优先,其次 Chez 各名
  (define self-runtimes "skiff scheme chez chez-scheme chezscheme")
  (define (bake-command) (or (getenv* "CHANDLER_BAKE") "bake"))

  (define (win?)
    (string-suffix? "nt" (current-machine-type)))

  ;; ── 落点(与 recipe 的 install-task target 对齐)──
  (define (self-libdir flags)
    (if (flag? flags 'global) "/usr/local/share/chez/lib"
        (string-append (home-dir) "/.local/share/chez/lib")))
  (define (self-bindir flags)
    (if (flag? flags 'global) "/usr/local/bin"
        (string-append (home-dir) "/.local/bin")))
  (define (self-launcher flags)
    (string-append (self-bindir flags) "/" (if (win?) "chandler.cmd" "chandler")))

  ;; bake 的已装清单(卸载据此删库,不依赖源码)
  (define (bake-manifest libdir) (string-append libdir "/.bake-install/chandler.files"))

  ;; ── install-self:bake install 装库 + 写启动器 ──
  (define (cmd-install-self root flags)
    (let* ([libdir   (self-libdir flags)]
           [launcher (self-launcher flags)]
           [global?  (flag? flags 'global)])
      ;; --force:已装则先卸库(bake install 遇清单会拒)
      (when (and (flag? flags 'force) (file-exists? (bake-manifest libdir)))
        (bake-uninstall root global?))
      ;; 1. 库树 → 委托 bake install(cwd = 源码 checkout,读其 recipe.ss)
      (run-check (bake-command)
                 (list (if global? "install-global" "install"))
                 (list (cons 'cwd root)))
      ;; 2. 运行时发现启动器(bake 不管这个)
      (write-text launcher (if (win?) (launcher-cmd libdir) (launcher-sh libdir)))
      (unless (win?) (run-check "chmod" (list "+x" launcher) '()))
      (printf "install ~a~%" launcher)
      (printf "已自装 chandler → ~a(库经 bake install)~%" libdir)
      (path-hint (self-bindir flags))
      0))

  ;; ── uninstall-self:据 bake 清单删库 + 删启动器(不依赖源码)──
  (define (cmd-uninstall-self root flags)
    (let ([libdir (self-libdir flags)]
          [launcher (self-launcher flags)])
      (uninstall-by-manifest libdir)
      (when (file-exists? launcher)
        (delete-file launcher) (sweep-empty-parents launcher)
        (printf "rm ~a~%" launcher))
      (printf "已卸载 chandler(自 ~a)~%" libdir)
      0))

  ;; 据 bake 清单(绝对路径,逐行)删文件 + 清空父目录 + 删清单本身
  (define (uninstall-by-manifest libdir)
    (let ([mf (bake-manifest libdir)])
      (if (file-exists? mf)
          (begin
            (for-each (lambda (f)
                        (when (file-exists? f) (delete-file f) (sweep-empty-parents f)))
                      (read-lines mf))
            (delete-file mf) (sweep-empty-parents mf))
          (fprintf (current-error-port)
                   "warning: 未找到 bake 安装清单 ~a(库可能未经 bake install 安装)~%" mf))))

  ;; 卸库(--force 复用):优先据清单删;有源码时也可 bake uninstall
  (define (bake-uninstall root global?)
    (uninstall-by-manifest (if global? "/usr/local/share/chez/lib"
                               (string-append (home-dir) "/.local/share/chez/lib"))))

  ;; ── 启动器模板(运行时发现:skiff → Chez;非 Chez 须过能力探测)──
  (define (launcher-sh home)
    (string-append
      "#!/bin/sh\n"
      "# chandler launcher — generated by `chandler install-self`; do not edit.\n"
      "# Prefer skiff, fall back to Chez scheme. Non-Chez runtimes must pass a\n"
      "# capability probe (skips early skiff stubs that only print a demo banner).\n"
      "CHANDLER_HOME=\"" home "\"\n"
      "export CHANDLER_HOME\n"
      "_prog_ok() {\n"
      "  printf '(import (chezscheme))(display \"CHANDLER_RT_OK\")' \\\n"
      "    | \"$1\" -q --program /dev/stdin 2>/dev/null | grep -q CHANDLER_RT_OK\n"
      "}\n"
      "for rt in " self-runtimes "; do\n"
      "  command -v \"$rt\" >/dev/null 2>&1 || continue\n"
      "  case \"$rt\" in\n"
      "    scheme|chez|chez-scheme|chezscheme) : ;;\n"
      "    *) _prog_ok \"$rt\" || continue ;;\n"
      "  esac\n"
      "  exec \"$rt\" -q --libdirs \"$CHANDLER_HOME\" --program \"$CHANDLER_HOME/chandler/cli/main.sps\" \"$@\"\n"
      "done\n"
      "echo \"chandler: no program-capable Scheme runtime found (need skiff or Chez Scheme).\" 1>&2\n"
      "exit 127\n"))

  (define (launcher-cmd home)
    (let ([h (backslashes home)])
      (string-append
        "@echo off\r\n"
        "setlocal\r\n"
        "set \"CHANDLER_HOME=" h "\"\r\n"
        "set \"RT=\"\r\n"
        "for %%r in (" self-runtimes ") do if not defined RT (\r\n"
        "  where %%r >nul 2>nul && set \"RT=%%r\"\r\n"
        ")\r\n"
        "if not defined RT (\r\n"
        "  echo chandler: no Scheme runtime found ^(need skiff or Chez Scheme^). 1>&2\r\n"
        "  exit /b 127\r\n"
        ")\r\n"
        "\"%RT%\" -q --libdirs \"%CHANDLER_HOME%\" --program \"%CHANDLER_HOME%\\chandler\\cli\\main.sps\" %*\r\n"
        "exit /b %errorlevel%\r\n")))

  (define (backslashes s)
    (list->string (map (lambda (c) (if (char=? c #\/) #\\ c)) (string->list s))))

  (define (path-hint bindir)
    (let ([p (or (getenv "PATH") "")])
      (unless (string-contains? p bindir)
        (printf "  提示:把 ~a 加入 PATH:export PATH=\"~a:$PATH\"~%" bindir bindir)))))
