#!chezscheme
;;; chandler/cli/selfinstall.ss --- chandler install-self / uninstall-self(对齐 bake,designs/08)
;;;
;;; 把 Chandler 自己的库树装到 ~/.local(默认),写一个**运行时发现**启动器:
;;; 优先 skiff,回退 Chez scheme(designs/06 双运行时;skiff 是 Chez 超集,--libdirs/--program 通用)。
;;; 这是「工具自装」——install.sh 只负责找个运行时把本命令跑起来,安装逻辑全在此。
;;;
;;; 布局(POSIX):
;;;   <prefix>/share/chez/lib/chandler.ss + chandler/**   ← 库树(= (import (chandler)) 可解析处)
;;;   <prefix>/bin/chandler                                ← 运行时发现启动器
;;;   <prefix>/share/chez/lib/.chandler-self.files         ← 已装文件清单(干净卸载)
;;; prefix:--prefix > --global(/usr/local)> $HOME/.local(默认)

(library (chandler cli selfinstall)
  (export cmd-install-self cmd-uninstall-self
          self-prefix self-home self-bindir self-launcher self-manifest
          self-runtimes)
  (import (chezscheme)
          (chandler proc)
          (chandler layout))

  ;; 运行时发现顺序:skiff 优先,其次 Chez 各名(petite 排除:与 bake 一致,留给编译型工具的约定)
  (define self-runtimes "skiff scheme chez chez-scheme chezscheme")

  (define (win?)
    (let ([m (current-machine-type)])
      (and (>= (string-length m) 2)
           (string=? "nt" (substring m (- (string-length m) 2) (string-length m))))))

  ;; ── prefix / 布局 ──
  (define (self-prefix flags)
    (cond
      [(flag flags 'prefix) => (lambda (p) p)]
      [(flag? flags 'global) (if (win?) "C:/Program Files" "/usr/local")]
      [(win?) (or (getenv "LOCALAPPDATA")
                  (let ([up (getenv "USERPROFILE")])
                    (and up (string-append up "/AppData/Local")))
                  (error 'install-self "无法解析 %LOCALAPPDATA%(用 --prefix)"))]
      [else (string-append (or (getenv "HOME") ".") "/.local")]))

  ;; home = 库树落点(= Chez 库搜索根,chandler.ss 直接在此)
  (define (self-home prefix)
    (if (win?) (string-append prefix "/chandler/lib")
        (string-append prefix "/share/chez/lib")))
  (define (self-bindir prefix)
    (if (win?) (string-append prefix "/chandler/bin") (string-append prefix "/bin")))
  (define (self-launcher prefix)
    (string-append (self-bindir prefix) "/" (if (win?) "chandler.cmd" "chandler")))
  (define (self-manifest home) (string-append home "/.chandler-self.files"))

  ;; ── 启动器模板(运行时发现:skiff → Chez)──
  (define (launcher-sh home)
    (string-append
      "#!/bin/sh\n"
      "# chandler launcher — generated by `chandler install-self`; do not edit.\n"
      "# Prefer skiff, fall back to Chez scheme. Non-Chez runtimes must pass a\n"
      "# capability probe (skips early skiff stubs that only print a demo banner).\n"
      "CHANDLER_HOME=\"" home "\"\n"
      "export CHANDLER_HOME\n"
      "_prog_ok() {\n"
      "  printf '(import (chezscheme))(display \"CHANDLER_RT_OK\")' \\\n"
      "    | \"$1\" -q --program /dev/stdin 2>/dev/null | grep -q CHANDLER_RT_OK\n"
      "}\n"
      "for rt in " self-runtimes "; do\n"
      "  command -v \"$rt\" >/dev/null 2>&1 || continue\n"
      "  case \"$rt\" in\n"
      "    scheme|chez|chez-scheme|chezscheme) : ;;\n"
      "    *) _prog_ok \"$rt\" || continue ;;\n"
      "  esac\n"
      "  exec \"$rt\" -q --libdirs \"$CHANDLER_HOME\" --program \"$CHANDLER_HOME/chandler/cli/main.sps\" \"$@\"\n"
      "done\n"
      "echo \"chandler: no program-capable Scheme runtime found (need skiff or Chez Scheme).\" 1>&2\n"
      "exit 127\n"))

  (define (launcher-cmd home)
    (let ([h (backslashes home)])
      (string-append
        "@echo off\r\n"
        "setlocal\r\n"
        "set \"CHANDLER_HOME=" h "\"\r\n"
        "set \"RT=\"\r\n"
        "for %%r in (" self-runtimes ") do if not defined RT (\r\n"
        "  where %%r >nul 2>nul && set \"RT=%%r\"\r\n"
        ")\r\n"
        "if not defined RT (\r\n"
        "  echo chandler: no Scheme runtime found ^(need skiff or Chez Scheme^). 1>&2\r\n"
        "  exit /b 127\r\n"
        ")\r\n"
        "\"%RT%\" -q --libdirs \"%CHANDLER_HOME%\" --program \"%CHANDLER_HOME%\\chandler\\cli\\main.sps\" %*\r\n"
        "exit /b %errorlevel%\r\n")))

  (define (backslashes s)
    (list->string (map (lambda (c) (if (char=? c #\/) #\\ c)) (string->list s))))

  ;; ── install-self ──
  (define (cmd-install-self root flags)
    (let* ([prefix   (self-prefix flags)]
           [home     (self-home prefix)]
           [bindir   (self-bindir prefix)]
           [launcher (self-launcher prefix)]
           [mf       (self-manifest home)])
      (when (and (file-exists? mf) (not (flag? flags 'force)))
        (error 'install-self
               (format "chandler 已自装于 ~a(先 chandler uninstall-self,或 --force)" home)))
      (let ([installed (install-tree! root home)])
        (write-text launcher (if (win?) (launcher-cmd home) (launcher-sh home)))
        (unless (win?) (chmod-exec launcher))
        (printf "install ~a~%" launcher)
        (set! installed (cons launcher installed))
        (ensure-parent mf)
        (call-with-output-file mf
          (lambda (p) (for-each (lambda (f) (display f p) (newline p))
                                (list-sort string<? installed)))
          'truncate)
        (printf "已自装 chandler → ~a~%" home)
        (path-hint bindir)
        0)))

  ;; 拷 chandler.ss + chandler/**(跳过 test/),返回已装绝对路径列表
  (define (install-tree! root home)
    (let ([installed '()])
      (define (cp abs rel)
        (let ([dst (string-append home "/" rel)])
          (ensure-parent dst)
          (run-check "cp" (list "-p" abs dst) '())
          (set! installed (cons dst installed))
          (printf "install ~a~%" dst)))
      ;; umbrella
      (cp (string-append root "/chandler.ss") "chandler.ss")
      ;; 子树:所有 .ss / .sps,排除 chandler/test/
      (for-each
        (lambda (abs)
          (let ([rel (strip-prefix abs (string-append root "/"))])
            (when (and (installable? rel) (not (in-test? rel)))
              (cp abs rel))))
        (files-under (string-append root "/chandler")))
      installed))

  (define (installable? rel)
    (let ([e (ext rel)]) (or (string=? e "ss") (string=? e "sps"))))
  (define (in-test? rel) (str-contains? rel "chandler/test/"))

  ;; ── uninstall-self ──
  (define (cmd-uninstall-self root flags)
    (let* ([prefix (self-prefix flags)]
           [home   (self-home prefix)]
           [mf     (self-manifest home)])
      (unless (file-exists? mf)
        (error 'uninstall-self (format "chandler 未自装于 ~a(无 ~a)" home mf)))
      (for-each
        (lambda (f)
          (when (file-exists? f)
            (delete-file f) (sweep-empty-parents f)
            (printf "rm ~a~%" f)))
        (file->lines mf))
      (delete-file mf) (sweep-empty-parents mf)
      (printf "已卸载 chandler(自 ~a)~%" home)
      0))

  ;; ── 文件工具 ──
  (define (files-under dir)
    (if (file-directory? dir)
        (let ([r (run-capture "find" (list dir "-type" "f"))])
          (if (= 0 (proc-result-code r))
              (filter (lambda (s) (> (string-length s) 0)) (lines (proc-result-out r)))
              '()))
        '()))

  (define (write-text path s)
    (ensure-parent path)
    (call-with-output-file path (lambda (p) (display s p)) 'truncate))
  (define (chmod-exec path) (run-check "chmod" (list "+x" path) '()))

  (define (ensure-parent path) (ensure-dir (parent-dir path)))
  (define (ensure-dir dir)
    (unless (or (string=? dir "") (file-directory? dir))
      (ensure-dir (parent-dir dir))
      (guard (e [#t (void)]) (mkdir dir))))
  (define (parent-dir path)
    (let loop ([i (- (string-length path) 1)])
      (cond [(< i 0) ""]
            [(char=? #\/ (string-ref path i)) (substring path 0 i)]
            [else (loop (- i 1))])))
  (define (sweep-empty-parents f)
    (let loop ([d (parent-dir f)])
      (when (and (> (string-length d) 1) (file-directory? d) (dir-empty? d))
        (guard (e [#t (void)]) (delete-directory d))
        (loop (parent-dir d)))))
  (define (dir-empty? d)
    (let ([r (run-capture "ls" (list "-A" d))])
      (and (= 0 (proc-result-code r))
           (null? (filter (lambda (s) (> (string-length s) 0)) (lines (proc-result-out r)))))))

  (define (file->lines path)
    (if (file-exists? path)
        (call-with-input-file path
          (lambda (p)
            (let loop ([acc '()])
              (let ([l (get-line p)])
                (if (eof-object? l) (reverse acc)
                    (loop (if (> (string-length l) 0) (cons l acc) acc)))))))
        '()))

  (define (path-hint bindir)
    (let ([p (or (getenv "PATH") "")])
      (unless (str-contains? p bindir)
        (printf "  提示:把 ~a 加入 PATH:export PATH=\"~a:$PATH\"~%" bindir bindir))))

  ;; ── 字符串 ──
  (define (flag flags k) (let ([p (assq k flags)]) (and p (cdr p))))
  (define (flag? flags k) (and (assq k flags) (cdr (assq k flags)) #t))
  (define (ext path)
    (let loop ([i (- (string-length path) 1)])
      (cond [(< i 0) ""]
            [(char=? #\/ (string-ref path i)) ""]
            [(char=? #\. (string-ref path i)) (substring path (+ i 1) (string-length path))]
            [else (loop (- i 1))])))
  (define (strip-prefix s pre)
    (let ([lp (string-length pre)])
      (if (and (>= (string-length s) lp) (string=? pre (substring s 0 lp)))
          (substring s lp (string-length s)) s)))
  (define (str-contains? hay needle)
    (let ([hn (string-length hay)] [nn (string-length needle)])
      (let loop ([i 0])
        (cond [(> (+ i nn) hn) #f]
              [(string=? (substring hay i (+ i nn)) needle) #t]
              [else (loop (+ i 1))]))))
  (define (lines s)
    (let loop ([chars (string->list s)] [cur '()] [acc '()])
      (cond
        [(null? chars) (reverse (cons (list->string (reverse cur)) acc))]
        [(char=? #\newline (car chars)) (loop (cdr chars) '() (cons (list->string (reverse cur)) acc))]
        [else (loop (cdr chars) (cons (car chars) cur) acc)]))))
